services:
  db:
      image: postgres:latest
      container_name: aerostream-db
      environment:
        POSTGRES_USER: admin
        POSTGRES_PASSWORD: ${AEROSTREAM_DB_PASSWORD:-local-dev-password}
        POSTGRES_DB: aerostream
        PGDATA: /var/lib/postgresql/data/pgdata # MANDATORY FOR POSTGRES 18+
      ports:
        - "5432:5432"
      volumes:
        - pgdata:/var/lib/postgresql/data

  ingestion-api:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: aerostream-api
    ports:
      - "5233:8080"
    depends_on:
      - db
    environment:
      - ConnectionStrings__DefaultConnection=Host=db;Database=aerostream;Username=admin;Password=${AEROSTREAM_DB_PASSWORD:-local-dev-password}

  # --- NEW: The Frontend UI ---
  dashboard:
    build:
      context: ./src/AeroStream.Dashboard
      dockerfile: Dockerfile
    container_name: aerostream-dashboard
    ports:
      - "5173:80" # Maps local 5173 to Nginx's internal 80
    depends_on:
      - ingestion-api

volumes:
  pgdata: